# Site settings
title: Arturo Aleé
email: arturo.alee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Arturo Aleé is a Senior Developer with a lot experience on performance and teams management 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arturo.alee.mx" # the base hostname & protocol for your site
twitter_username: aalee
github_username:  aalee

# Build settings
markdown: kramdown
